name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
            LD_LIBRARY_PATH: $GITHUB_WORKSPACE/lib
    strategy:
      matrix:
        julia-version: ['1.2', '1', 'nightly']
        julia-arch: [x64, x86]
        os: [ubuntu-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cifapi_action
      - name: check the file location
        run: |
                ls $GITHUB_WORKSPACE/lib
                set
      - uses: julia-actions/setup-julia@latest
        with:
           version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
